#!/bin/bash

source .env

mapfile -t sensitive < <(find aws/ -name "*.tfstate*" -or -name "*.tfvars" -or -name "*.tfplan")

length=${#sensitive[@]}

if [ $length -eq 0 ]; then
	echo "Missing mandatory files locally!"
	echo "If you are absolutely sure that you want to push those changes: git push --no-verify"
else
	echo "Uploading to cloud..."
	for sens in "${sensitive[@]}"; do
		upload_output=$(aws s3 cp ${sens} s3://$PRIVATE_S3_BUCKET/dev/${sens} 2>&1)
		if [ $? -eq 0 ]; then
			echo "Uploaded ${sens} successfully!"
		else
			echo "Error uploading ${sens}!"
			echo ${upload_output}
			exit 1
		fi
	done
fi
