services:
  localstack:
    image: localstack/localstack-pro:latest
    ports:
      - "4566:4566"
    environment:
      LOCALSTACK_AUTH_TOKEN: ${LOCALSTACK_AUTH_TOKEN}
      PERSISTENCE: "1"
      DEBUG: "0"
      PROVIDER_OVERRIDE_DYNAMODB: "v2"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - localstack-data:/var/lib/localstack

volumes:
  localstack-data:
